// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantStore.Api.Data;

#nullable disable

namespace PlantStore.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250613100259_AddUsers")]
    partial class AddUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("PlantStore.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Byliny"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trawy ozdobne"
                        });
                });

            modelBuilder.Entity("PlantStore.Api.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Odmiana deserowa, doskonała na przetwory.",
                            ImageUrl = "/images/sliwa.jpg",
                            InStock = 50,
                            Name = "Śliwa Węgierka",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Duże, słodkie jabłka o czerwonej skórce.",
                            ImageUrl = "/images/jablon.jpg",
                            InStock = 40,
                            Name = "Jabłoń Ligol",
                            Price = 24.99m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Długo przechowująca się odmiana gruszy.",
                            ImageUrl = "/images/grusza.jpg",
                            InStock = 35,
                            Name = "Grusza Konferencja",
                            Price = 22.50m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Wczesna odmiana o dużych, ciemnoczerwonych owocach.",
                            ImageUrl = "/images/czeresnia.jpg",
                            InStock = 20,
                            Name = "Czereśnia Burlat",
                            Price = 27.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Soczysta i bardzo słodka odmiana.",
                            ImageUrl = "/images/brzoskwinia.jpg",
                            InStock = 30,
                            Name = "Brzoskwinia Harnaś",
                            Price = 18.75m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Wczesna odmiana moreli, idealna do sadów.",
                            ImageUrl = "/images/morela.jpg",
                            InStock = 25,
                            Name = "Morela Early Orange",
                            Price = 20.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Popularna krzewinka o kwaśnych owocach.",
                            ImageUrl = "/images/porzeczka.jpg",
                            InStock = 60,
                            Name = "Porzeczka Czerwona",
                            Price = 12.99m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Odmiana jesienna, plenna.",
                            ImageUrl = "/images/malina.jpg",
                            InStock = 70,
                            Name = "Malina Polana",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Wysoka zawartość antyoksydantów.",
                            ImageUrl = "/images/borowka.jpg",
                            InStock = 45,
                            Name = "Borówka Amerykańska",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Nadaje się do produkcji czerwonego wina.",
                            ImageUrl = "/images/winorosl.jpg",
                            InStock = 15,
                            Name = "Winorośl Regent",
                            Price = 32.50m
                        });
                });

            modelBuilder.Entity("PlantStore.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PlantStore.Api.Models.Product", b =>
                {
                    b.HasOne("PlantStore.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PlantStore.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
